# Site
name: "NC AI Blog"
title: "NC AI Blog"
description: "Unofficial Blog"
meta_description: "Unofficial Blog"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 10
baseurl: ''
email: 'maybedy@ncsoft.com'
# google_analytics: ''
# disqus: 'nc-ai'

# Authors
authors:
  doyun:
    name: Doyun Kim
    display_name: 김도윤
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: maybedy@ncsoft.com
    web: https://maybedy.github.io
    twitter:
    description: "AI Center 온갖일 다함"
  
  inseok:
    name: Inseok Oh
    display_name: 오인석
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: ohinsuk@ncsoft.com
    web: 
    description: "Game AI Lab 강화학습팀"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  

# Other
markdown: kramdown
highlighter: rouge

defaults: 
  - scope:
      path: "assets/images"
    values:
      image: true

sass:
  sass_dir: _sass

# Collections
collections:
  research:
    output: true
    title: Research
    title_singular: Research
    description: 연구 이야기들
    sequence: 1 // for ordering collections
  life:
    output: true
    title: Life
    title_singular: Life
    description: 생활들
    sequence: 2
  publication:
    output: true
    title: Publication
    title_singular: Publication
    description: 논문 및 학회
    sequence: 3
  press:
    output: true
    title: Press
    title_singular: Press
    description: 관련 기사
    sequence: 4  