# Site
name: "NCAI"
title: "NCAI"
description: "Unofficial Blogging"
meta_description: "Unofficial Blogging"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: ''
email: 'maybedy@ncsoft.com'
google_analytics: ''
disqus: 'nc-ai'

# Authors
authors:
  doyun:
    name: Doyun
    display_name: Doyun
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: maybedy@ncsoft.com
    web: https://maybedy.github.io
    twitter:
    description: "Unofficial blog admin"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: post_list
  permalinks:
    category: '/category/:name/'

# Other
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass